/*
 * Copyright 2026 Turing Software LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * Generated by npt_protocol.py -- do not edit.
 *
 * Command structs and encode/decode for id3d12descriptorheap.
 */

#ifndef NPT_PROTOCOL_HOST_ID3D12DESCRIPTORHEAP_H
#define NPT_PROTOCOL_HOST_ID3D12DESCRIPTORHEAP_H

#include "npt_protocol_host_structs.h"
#include "npt_protocol_host_dispatch_types.h"

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-parameter"
#pragma GCC diagnostic ignored "-Wpointer-arith"

/*
 * ID3D12DescriptorHeap::GetDesc
 */

struct npt_command_ID3D12DescriptorHeap_GetDesc {
    void *_self;
    D3D12_DESCRIPTOR_HEAP_DESC ret;
};

static inline void
npt_decode_ID3D12DescriptorHeap_GetDesc_args_temp(struct npt_cs_decoder *dec,
                                                  struct npt_command_ID3D12DescriptorHeap_GetDesc *args)
{
    /* Decode input parameters from the wire */
    /* Allocate temp storage for output-only parameters */
}

static inline void
npt_replace_ID3D12DescriptorHeap_GetDesc_args_handle(struct npt_dispatch_context *ctx, struct npt_command_ID3D12DescriptorHeap_GetDesc *args)
{
}

static inline void
npt_encode_ID3D12DescriptorHeap_GetDesc_reply(struct npt_cs_encoder *enc,
                                              const struct npt_command_ID3D12DescriptorHeap_GetDesc *args)
{
    struct npt_reply_header _reply = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12DescriptorHeap,
                                 NPT_METHOD_ID3D12DescriptorHeap_GetDesc),
        .cmd_return = 0,
    };
    npt_cs_encoder_write(enc, sizeof(_reply), &_reply, sizeof(_reply));
    npt_encode_D3D12_DESCRIPTOR_HEAP_DESC(enc, &args->ret);
}

static inline void
npt_dispatch_ID3D12DescriptorHeap_GetDesc(struct npt_dispatch_context *ctx,
                                          uint32_t cmd_flags,
                                          uint64_t object_id)
{
    struct npt_command_ID3D12DescriptorHeap_GetDesc args;
    memset(&args, 0, sizeof(args));

    npt_decode_ID3D12DescriptorHeap_GetDesc_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_ID3D12DESCRIPTORHEAP);
    if (!args._self) {
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_ID3D12DescriptorHeap_GetDesc_args_handle(ctx, &args);

    PFN_ID3D12DescriptorHeap_GetDesc _original = NPT_COM_VTBL_FUNC(
        PFN_ID3D12DescriptorHeap_GetDesc, npt_com_vtable(args._self),
        NPT_VTBL_ID3D12DescriptorHeap_GetDesc);

    if (ctx->id3d12descriptorheap_dispatch_overrides && ctx->id3d12descriptorheap_dispatch_overrides->GetDesc) {
        args.ret = ctx->id3d12descriptorheap_dispatch_overrides->GetDesc(ctx, &args, _original);
    } else {
        args.ret = _original(args._self);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_ID3D12DescriptorHeap_GetDesc_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}

/*
 * ID3D12DescriptorHeap::GetCPUDescriptorHandleForHeapStart
 */

struct npt_command_ID3D12DescriptorHeap_GetCPUDescriptorHandleForHeapStart {
    void *_self;
    D3D12_CPU_DESCRIPTOR_HANDLE ret;
};

static inline void
npt_decode_ID3D12DescriptorHeap_GetCPUDescriptorHandleForHeapStart_args_temp(struct npt_cs_decoder *dec,
                                                                             struct npt_command_ID3D12DescriptorHeap_GetCPUDescriptorHandleForHeapStart *args)
{
    /* Decode input parameters from the wire */
    /* Allocate temp storage for output-only parameters */
}

static inline void
npt_replace_ID3D12DescriptorHeap_GetCPUDescriptorHandleForHeapStart_args_handle(struct npt_dispatch_context *ctx, struct npt_command_ID3D12DescriptorHeap_GetCPUDescriptorHandleForHeapStart *args)
{
}

static inline void
npt_encode_ID3D12DescriptorHeap_GetCPUDescriptorHandleForHeapStart_reply(struct npt_cs_encoder *enc,
                                                                         const struct npt_command_ID3D12DescriptorHeap_GetCPUDescriptorHandleForHeapStart *args)
{
    struct npt_reply_header _reply = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12DescriptorHeap,
                                 NPT_METHOD_ID3D12DescriptorHeap_GetCPUDescriptorHandleForHeapStart),
        .cmd_return = 0,
    };
    npt_cs_encoder_write(enc, sizeof(_reply), &_reply, sizeof(_reply));
    npt_encode_D3D12_CPU_DESCRIPTOR_HANDLE(enc, &args->ret);
}

static inline void
npt_dispatch_ID3D12DescriptorHeap_GetCPUDescriptorHandleForHeapStart(struct npt_dispatch_context *ctx,
                                                                     uint32_t cmd_flags,
                                                                     uint64_t object_id)
{
    struct npt_command_ID3D12DescriptorHeap_GetCPUDescriptorHandleForHeapStart args;
    memset(&args, 0, sizeof(args));

    npt_decode_ID3D12DescriptorHeap_GetCPUDescriptorHandleForHeapStart_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_ID3D12DESCRIPTORHEAP);
    if (!args._self) {
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_ID3D12DescriptorHeap_GetCPUDescriptorHandleForHeapStart_args_handle(ctx, &args);

    PFN_ID3D12DescriptorHeap_GetCPUDescriptorHandleForHeapStart _original = NPT_COM_VTBL_FUNC(
        PFN_ID3D12DescriptorHeap_GetCPUDescriptorHandleForHeapStart, npt_com_vtable(args._self),
        NPT_VTBL_ID3D12DescriptorHeap_GetCPUDescriptorHandleForHeapStart);

    if (ctx->id3d12descriptorheap_dispatch_overrides && ctx->id3d12descriptorheap_dispatch_overrides->GetCPUDescriptorHandleForHeapStart) {
        args.ret = ctx->id3d12descriptorheap_dispatch_overrides->GetCPUDescriptorHandleForHeapStart(ctx, &args, _original);
    } else {
        args.ret = _original(args._self);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_ID3D12DescriptorHeap_GetCPUDescriptorHandleForHeapStart_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}

/*
 * ID3D12DescriptorHeap::GetGPUDescriptorHandleForHeapStart
 */

struct npt_command_ID3D12DescriptorHeap_GetGPUDescriptorHandleForHeapStart {
    void *_self;
    D3D12_GPU_DESCRIPTOR_HANDLE ret;
};

static inline void
npt_decode_ID3D12DescriptorHeap_GetGPUDescriptorHandleForHeapStart_args_temp(struct npt_cs_decoder *dec,
                                                                             struct npt_command_ID3D12DescriptorHeap_GetGPUDescriptorHandleForHeapStart *args)
{
    /* Decode input parameters from the wire */
    /* Allocate temp storage for output-only parameters */
}

static inline void
npt_replace_ID3D12DescriptorHeap_GetGPUDescriptorHandleForHeapStart_args_handle(struct npt_dispatch_context *ctx, struct npt_command_ID3D12DescriptorHeap_GetGPUDescriptorHandleForHeapStart *args)
{
}

static inline void
npt_encode_ID3D12DescriptorHeap_GetGPUDescriptorHandleForHeapStart_reply(struct npt_cs_encoder *enc,
                                                                         const struct npt_command_ID3D12DescriptorHeap_GetGPUDescriptorHandleForHeapStart *args)
{
    struct npt_reply_header _reply = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12DescriptorHeap,
                                 NPT_METHOD_ID3D12DescriptorHeap_GetGPUDescriptorHandleForHeapStart),
        .cmd_return = 0,
    };
    npt_cs_encoder_write(enc, sizeof(_reply), &_reply, sizeof(_reply));
    npt_encode_D3D12_GPU_DESCRIPTOR_HANDLE(enc, &args->ret);
}

static inline void
npt_dispatch_ID3D12DescriptorHeap_GetGPUDescriptorHandleForHeapStart(struct npt_dispatch_context *ctx,
                                                                     uint32_t cmd_flags,
                                                                     uint64_t object_id)
{
    struct npt_command_ID3D12DescriptorHeap_GetGPUDescriptorHandleForHeapStart args;
    memset(&args, 0, sizeof(args));

    npt_decode_ID3D12DescriptorHeap_GetGPUDescriptorHandleForHeapStart_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_ID3D12DESCRIPTORHEAP);
    if (!args._self) {
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_ID3D12DescriptorHeap_GetGPUDescriptorHandleForHeapStart_args_handle(ctx, &args);

    PFN_ID3D12DescriptorHeap_GetGPUDescriptorHandleForHeapStart _original = NPT_COM_VTBL_FUNC(
        PFN_ID3D12DescriptorHeap_GetGPUDescriptorHandleForHeapStart, npt_com_vtable(args._self),
        NPT_VTBL_ID3D12DescriptorHeap_GetGPUDescriptorHandleForHeapStart);

    if (ctx->id3d12descriptorheap_dispatch_overrides && ctx->id3d12descriptorheap_dispatch_overrides->GetGPUDescriptorHandleForHeapStart) {
        args.ret = ctx->id3d12descriptorheap_dispatch_overrides->GetGPUDescriptorHandleForHeapStart(ctx, &args, _original);
    } else {
        args.ret = _original(args._self);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_ID3D12DescriptorHeap_GetGPUDescriptorHandleForHeapStart_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}


#pragma GCC diagnostic pop

#endif /* NPT_PROTOCOL_HOST_ID3D12DESCRIPTORHEAP_H */
