/*
 * Copyright 2026 Turing Software LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * Generated by npt_protocol.py -- do not edit.
 *
 * Command structs and encode/decode for id3d12commandqueue.
 */

#ifndef NPT_PROTOCOL_HOST_ID3D12COMMANDQUEUE_H
#define NPT_PROTOCOL_HOST_ID3D12COMMANDQUEUE_H

#include "npt_protocol_host_structs.h"
#include "npt_protocol_host_dispatch_types.h"

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-parameter"
#pragma GCC diagnostic ignored "-Wpointer-arith"

/*
 * ID3D12CommandQueue::UpdateTileMappings
 */

struct npt_command_ID3D12CommandQueue_UpdateTileMappings {
    void *_self;
    ID3D12Resource * pResource;
    UINT NumResourceRegions;
    const D3D12_TILED_RESOURCE_COORDINATE * pResourceRegionStartCoordinates;
    const D3D12_TILE_REGION_SIZE * pResourceRegionSizes;
    ID3D12Heap * pHeap;
    UINT NumRanges;
    const D3D12_TILE_RANGE_FLAGS * pRangeFlags;
    const UINT * pHeapRangeStartOffsets;
    const UINT * pRangeTileCounts;
    D3D12_TILE_MAPPING_FLAGS Flags;
};

static inline void
npt_decode_ID3D12CommandQueue_UpdateTileMappings_args_temp(struct npt_cs_decoder *dec,
                                                           struct npt_command_ID3D12CommandQueue_UpdateTileMappings *args)
{
    /* Decode input parameters from the wire */
    {
        npt_object_id _id;
        npt_decode_uint64_t(dec, &_id);
        args->pResource = (ID3D12Resource *)npt_object_from_id(_id);
    }
    npt_decode_UINT(dec, &args->NumResourceRegions);
    if (npt_peek_array_count(dec)) {
        const uint64_t _count = npt_decode_array_count_unchecked(dec);
        args->pResourceRegionStartCoordinates = npt_cs_decoder_alloc_temp_array(dec, sizeof(D3D12_TILED_RESOURCE_COORDINATE), _count);
        if (!args->pResourceRegionStartCoordinates) return;
        for (uint32_t _i = 0; _i < (uint32_t)_count; _i++)
            npt_decode_D3D12_TILED_RESOURCE_COORDINATE(dec, (D3D12_TILED_RESOURCE_COORDINATE *)&args->pResourceRegionStartCoordinates[_i]);
    } else {
        (void)npt_decode_array_count_unchecked(dec); /* consume the 0 */
        (void)(args->NumResourceRegions); /* unused: count_expr from registry */
        args->pResourceRegionStartCoordinates = NULL;
    }
    if (npt_peek_array_count(dec)) {
        const uint64_t _count = npt_decode_array_count_unchecked(dec);
        args->pResourceRegionSizes = npt_cs_decoder_alloc_temp_array(dec, sizeof(D3D12_TILE_REGION_SIZE), _count);
        if (!args->pResourceRegionSizes) return;
        for (uint32_t _i = 0; _i < (uint32_t)_count; _i++)
            npt_decode_D3D12_TILE_REGION_SIZE(dec, (D3D12_TILE_REGION_SIZE *)&args->pResourceRegionSizes[_i]);
    } else {
        (void)npt_decode_array_count_unchecked(dec); /* consume the 0 */
        (void)(args->NumResourceRegions); /* unused: count_expr from registry */
        args->pResourceRegionSizes = NULL;
    }
    {
        npt_object_id _id;
        npt_decode_uint64_t(dec, &_id);
        args->pHeap = (ID3D12Heap *)npt_object_from_id(_id);
    }
    npt_decode_UINT(dec, &args->NumRanges);
    if (npt_peek_array_count(dec)) {
        const uint64_t _count = npt_decode_array_count_unchecked(dec);
        args->pRangeFlags = npt_cs_decoder_alloc_temp_array(dec, sizeof(D3D12_TILE_RANGE_FLAGS), _count);
        if (!args->pRangeFlags) return;
        npt_decode_D3D12_TILE_RANGE_FLAGS_array(dec, (D3D12_TILE_RANGE_FLAGS *)args->pRangeFlags, _count);
    } else {
        (void)npt_decode_array_count_unchecked(dec); /* consume the 0 */
        (void)(args->NumRanges); /* unused: count_expr from registry */
        args->pRangeFlags = NULL;
    }
    if (npt_peek_array_count(dec)) {
        const uint64_t _count = npt_decode_array_count_unchecked(dec);
        args->pHeapRangeStartOffsets = npt_cs_decoder_alloc_temp_array(dec, sizeof(UINT), _count);
        if (!args->pHeapRangeStartOffsets) return;
        npt_decode_UINT_array(dec, (UINT *)args->pHeapRangeStartOffsets, _count);
    } else {
        (void)npt_decode_array_count_unchecked(dec); /* consume the 0 */
        (void)(args->NumRanges); /* unused: count_expr from registry */
        args->pHeapRangeStartOffsets = NULL;
    }
    if (npt_peek_array_count(dec)) {
        const uint64_t _count = npt_decode_array_count_unchecked(dec);
        args->pRangeTileCounts = npt_cs_decoder_alloc_temp_array(dec, sizeof(UINT), _count);
        if (!args->pRangeTileCounts) return;
        npt_decode_UINT_array(dec, (UINT *)args->pRangeTileCounts, _count);
    } else {
        (void)npt_decode_array_count_unchecked(dec); /* consume the 0 */
        (void)(args->NumRanges); /* unused: count_expr from registry */
        args->pRangeTileCounts = NULL;
    }
    npt_decode_D3D12_TILE_MAPPING_FLAGS(dec, &args->Flags);
    /* Allocate temp storage for output-only parameters */










}

static inline void
npt_replace_ID3D12CommandQueue_UpdateTileMappings_args_handle(struct npt_dispatch_context *ctx, struct npt_command_ID3D12CommandQueue_UpdateTileMappings *args)
{
    args->pResource = npt_cs_handle_lookup(ctx, (npt_object_id)(uintptr_t)args->pResource, NPT_OBJECT_TYPE_ID3D12RESOURCE);
    args->pHeap = npt_cs_handle_lookup(ctx, (npt_object_id)(uintptr_t)args->pHeap, NPT_OBJECT_TYPE_ID3D12HEAP);
}

static inline void
npt_encode_ID3D12CommandQueue_UpdateTileMappings_reply(struct npt_cs_encoder *enc,
                                                       const struct npt_command_ID3D12CommandQueue_UpdateTileMappings *args)
{
    struct npt_reply_header _reply = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12CommandQueue,
                                 NPT_METHOD_ID3D12CommandQueue_UpdateTileMappings),
        .cmd_return = 0,
    };
    npt_cs_encoder_write(enc, sizeof(_reply), &_reply, sizeof(_reply));
}

static inline void
npt_dispatch_ID3D12CommandQueue_UpdateTileMappings(struct npt_dispatch_context *ctx,
                                                   uint32_t cmd_flags,
                                                   uint64_t object_id)
{
    struct npt_command_ID3D12CommandQueue_UpdateTileMappings args;
    memset(&args, 0, sizeof(args));

    npt_decode_ID3D12CommandQueue_UpdateTileMappings_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_ID3D12COMMANDQUEUE);
    if (!args._self) {
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_ID3D12CommandQueue_UpdateTileMappings_args_handle(ctx, &args);

    PFN_ID3D12CommandQueue_UpdateTileMappings _original = NPT_COM_VTBL_FUNC(
        PFN_ID3D12CommandQueue_UpdateTileMappings, npt_com_vtable(args._self),
        NPT_VTBL_ID3D12CommandQueue_UpdateTileMappings);

    if (ctx->id3d12commandqueue_dispatch_overrides && ctx->id3d12commandqueue_dispatch_overrides->UpdateTileMappings) {
        ctx->id3d12commandqueue_dispatch_overrides->UpdateTileMappings(ctx, &args, _original);
    } else {
        _original(args._self, args.pResource, args.NumResourceRegions, args.pResourceRegionStartCoordinates, args.pResourceRegionSizes, args.pHeap, args.NumRanges, args.pRangeFlags, args.pHeapRangeStartOffsets, args.pRangeTileCounts, args.Flags);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_ID3D12CommandQueue_UpdateTileMappings_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}

/*
 * ID3D12CommandQueue::CopyTileMappings
 */

struct npt_command_ID3D12CommandQueue_CopyTileMappings {
    void *_self;
    ID3D12Resource * pDstResource;
    const D3D12_TILED_RESOURCE_COORDINATE * pDstRegionStartCoordinate;
    ID3D12Resource * pSrcResource;
    const D3D12_TILED_RESOURCE_COORDINATE * pSrcRegionStartCoordinate;
    const D3D12_TILE_REGION_SIZE * pRegionSize;
    D3D12_TILE_MAPPING_FLAGS Flags;
};

static inline void
npt_decode_ID3D12CommandQueue_CopyTileMappings_args_temp(struct npt_cs_decoder *dec,
                                                         struct npt_command_ID3D12CommandQueue_CopyTileMappings *args)
{
    /* Decode input parameters from the wire */
    {
        npt_object_id _id;
        npt_decode_uint64_t(dec, &_id);
        args->pDstResource = (ID3D12Resource *)npt_object_from_id(_id);
    }
    if (npt_decode_simple_pointer(dec)) {
        args->pDstRegionStartCoordinate = npt_cs_decoder_alloc_temp(dec, sizeof(D3D12_TILED_RESOURCE_COORDINATE));
        if (!args->pDstRegionStartCoordinate) return;
        npt_decode_D3D12_TILED_RESOURCE_COORDINATE(dec, (D3D12_TILED_RESOURCE_COORDINATE *)args->pDstRegionStartCoordinate);
    } else {
        args->pDstRegionStartCoordinate = NULL;
        npt_cs_decoder_set_fatal(dec); /* non-optional pointer is NULL */
    }
    {
        npt_object_id _id;
        npt_decode_uint64_t(dec, &_id);
        args->pSrcResource = (ID3D12Resource *)npt_object_from_id(_id);
    }
    if (npt_decode_simple_pointer(dec)) {
        args->pSrcRegionStartCoordinate = npt_cs_decoder_alloc_temp(dec, sizeof(D3D12_TILED_RESOURCE_COORDINATE));
        if (!args->pSrcRegionStartCoordinate) return;
        npt_decode_D3D12_TILED_RESOURCE_COORDINATE(dec, (D3D12_TILED_RESOURCE_COORDINATE *)args->pSrcRegionStartCoordinate);
    } else {
        args->pSrcRegionStartCoordinate = NULL;
        npt_cs_decoder_set_fatal(dec); /* non-optional pointer is NULL */
    }
    if (npt_decode_simple_pointer(dec)) {
        args->pRegionSize = npt_cs_decoder_alloc_temp(dec, sizeof(D3D12_TILE_REGION_SIZE));
        if (!args->pRegionSize) return;
        npt_decode_D3D12_TILE_REGION_SIZE(dec, (D3D12_TILE_REGION_SIZE *)args->pRegionSize);
    } else {
        args->pRegionSize = NULL;
        npt_cs_decoder_set_fatal(dec); /* non-optional pointer is NULL */
    }
    npt_decode_D3D12_TILE_MAPPING_FLAGS(dec, &args->Flags);
    /* Allocate temp storage for output-only parameters */






}

static inline void
npt_replace_ID3D12CommandQueue_CopyTileMappings_args_handle(struct npt_dispatch_context *ctx, struct npt_command_ID3D12CommandQueue_CopyTileMappings *args)
{
    args->pDstResource = npt_cs_handle_lookup(ctx, (npt_object_id)(uintptr_t)args->pDstResource, NPT_OBJECT_TYPE_ID3D12RESOURCE);
    args->pSrcResource = npt_cs_handle_lookup(ctx, (npt_object_id)(uintptr_t)args->pSrcResource, NPT_OBJECT_TYPE_ID3D12RESOURCE);
}

static inline void
npt_encode_ID3D12CommandQueue_CopyTileMappings_reply(struct npt_cs_encoder *enc,
                                                     const struct npt_command_ID3D12CommandQueue_CopyTileMappings *args)
{
    struct npt_reply_header _reply = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12CommandQueue,
                                 NPT_METHOD_ID3D12CommandQueue_CopyTileMappings),
        .cmd_return = 0,
    };
    npt_cs_encoder_write(enc, sizeof(_reply), &_reply, sizeof(_reply));
}

static inline void
npt_dispatch_ID3D12CommandQueue_CopyTileMappings(struct npt_dispatch_context *ctx,
                                                 uint32_t cmd_flags,
                                                 uint64_t object_id)
{
    struct npt_command_ID3D12CommandQueue_CopyTileMappings args;
    memset(&args, 0, sizeof(args));

    npt_decode_ID3D12CommandQueue_CopyTileMappings_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_ID3D12COMMANDQUEUE);
    if (!args._self) {
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_ID3D12CommandQueue_CopyTileMappings_args_handle(ctx, &args);

    PFN_ID3D12CommandQueue_CopyTileMappings _original = NPT_COM_VTBL_FUNC(
        PFN_ID3D12CommandQueue_CopyTileMappings, npt_com_vtable(args._self),
        NPT_VTBL_ID3D12CommandQueue_CopyTileMappings);

    if (ctx->id3d12commandqueue_dispatch_overrides && ctx->id3d12commandqueue_dispatch_overrides->CopyTileMappings) {
        ctx->id3d12commandqueue_dispatch_overrides->CopyTileMappings(ctx, &args, _original);
    } else {
        _original(args._self, args.pDstResource, args.pDstRegionStartCoordinate, args.pSrcResource, args.pSrcRegionStartCoordinate, args.pRegionSize, args.Flags);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_ID3D12CommandQueue_CopyTileMappings_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}

/*
 * ID3D12CommandQueue::ExecuteCommandLists
 */

struct npt_command_ID3D12CommandQueue_ExecuteCommandLists {
    void *_self;
    UINT NumCommandLists;
    ID3D12CommandList ** ppCommandLists;
};

static inline void
npt_decode_ID3D12CommandQueue_ExecuteCommandLists_args_temp(struct npt_cs_decoder *dec,
                                                            struct npt_command_ID3D12CommandQueue_ExecuteCommandLists *args)
{
    /* Decode input parameters from the wire */
    npt_decode_UINT(dec, &args->NumCommandLists);
    {
        const uint64_t _count = npt_decode_array_count_unchecked(dec);
        if (_count) {
            args->ppCommandLists = npt_cs_decoder_alloc_temp_array(dec, sizeof(void *), _count);
            if (!args->ppCommandLists) return;
            for (uint64_t _i = 0; _i < _count; _i++) {
                npt_object_id _id;
                npt_decode_uint64_t(dec, &_id);
                args->ppCommandLists[_i] = npt_object_from_id(_id);
            }
        } else {
            args->ppCommandLists = NULL;
        }
    }
    /* Allocate temp storage for output-only parameters */


}

static inline void
npt_replace_ID3D12CommandQueue_ExecuteCommandLists_args_handle(struct npt_dispatch_context *ctx, struct npt_command_ID3D12CommandQueue_ExecuteCommandLists *args)
{
    if (args->ppCommandLists) {
        for (uint32_t _i = 0; _i < (uint32_t)(args->NumCommandLists); _i++)
            args->ppCommandLists[_i] = npt_cs_handle_lookup(ctx,
                (npt_object_id)(uintptr_t)args->ppCommandLists[_i], NPT_OBJECT_TYPE_ID3D12COMMANDLIST);
    }
}

static inline void
npt_encode_ID3D12CommandQueue_ExecuteCommandLists_reply(struct npt_cs_encoder *enc,
                                                        const struct npt_command_ID3D12CommandQueue_ExecuteCommandLists *args)
{
    struct npt_reply_header _reply = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12CommandQueue,
                                 NPT_METHOD_ID3D12CommandQueue_ExecuteCommandLists),
        .cmd_return = 0,
    };
    npt_cs_encoder_write(enc, sizeof(_reply), &_reply, sizeof(_reply));
}

static inline void
npt_dispatch_ID3D12CommandQueue_ExecuteCommandLists(struct npt_dispatch_context *ctx,
                                                    uint32_t cmd_flags,
                                                    uint64_t object_id)
{
    struct npt_command_ID3D12CommandQueue_ExecuteCommandLists args;
    memset(&args, 0, sizeof(args));

    npt_decode_ID3D12CommandQueue_ExecuteCommandLists_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_ID3D12COMMANDQUEUE);
    if (!args._self) {
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_ID3D12CommandQueue_ExecuteCommandLists_args_handle(ctx, &args);

    PFN_ID3D12CommandQueue_ExecuteCommandLists _original = NPT_COM_VTBL_FUNC(
        PFN_ID3D12CommandQueue_ExecuteCommandLists, npt_com_vtable(args._self),
        NPT_VTBL_ID3D12CommandQueue_ExecuteCommandLists);

    if (ctx->id3d12commandqueue_dispatch_overrides && ctx->id3d12commandqueue_dispatch_overrides->ExecuteCommandLists) {
        ctx->id3d12commandqueue_dispatch_overrides->ExecuteCommandLists(ctx, &args, _original);
    } else {
        _original(args._self, args.NumCommandLists, args.ppCommandLists);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_ID3D12CommandQueue_ExecuteCommandLists_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}

/*
 * ID3D12CommandQueue::SetMarker
 */

struct npt_command_ID3D12CommandQueue_SetMarker {
    void *_self;
    UINT Metadata;
    const void * pData;
    UINT Size;
};

static inline void
npt_decode_ID3D12CommandQueue_SetMarker_args_temp(struct npt_cs_decoder *dec,
                                                  struct npt_command_ID3D12CommandQueue_SetMarker *args)
{
    /* Decode input parameters from the wire */
    npt_decode_UINT(dec, &args->Metadata);
    {
        const uint64_t _blob_size = npt_decode_array_count_unchecked(dec);
        if (_blob_size) {
            args->pData = npt_cs_decoder_alloc_temp(dec, _blob_size);
            if (!args->pData) return;
            npt_decode_blob_array(dec, (void *)args->pData, _blob_size);
        } else {
            args->pData = NULL;
        }
    }
    npt_decode_UINT(dec, &args->Size);
    /* Allocate temp storage for output-only parameters */



}

static inline void
npt_replace_ID3D12CommandQueue_SetMarker_args_handle(struct npt_dispatch_context *ctx, struct npt_command_ID3D12CommandQueue_SetMarker *args)
{
}

static inline void
npt_encode_ID3D12CommandQueue_SetMarker_reply(struct npt_cs_encoder *enc,
                                              const struct npt_command_ID3D12CommandQueue_SetMarker *args)
{
    struct npt_reply_header _reply = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12CommandQueue,
                                 NPT_METHOD_ID3D12CommandQueue_SetMarker),
        .cmd_return = 0,
    };
    npt_cs_encoder_write(enc, sizeof(_reply), &_reply, sizeof(_reply));
}

static inline void
npt_dispatch_ID3D12CommandQueue_SetMarker(struct npt_dispatch_context *ctx,
                                          uint32_t cmd_flags,
                                          uint64_t object_id)
{
    struct npt_command_ID3D12CommandQueue_SetMarker args;
    memset(&args, 0, sizeof(args));

    npt_decode_ID3D12CommandQueue_SetMarker_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_ID3D12COMMANDQUEUE);
    if (!args._self) {
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_ID3D12CommandQueue_SetMarker_args_handle(ctx, &args);

    PFN_ID3D12CommandQueue_SetMarker _original = NPT_COM_VTBL_FUNC(
        PFN_ID3D12CommandQueue_SetMarker, npt_com_vtable(args._self),
        NPT_VTBL_ID3D12CommandQueue_SetMarker);

    if (ctx->id3d12commandqueue_dispatch_overrides && ctx->id3d12commandqueue_dispatch_overrides->SetMarker) {
        ctx->id3d12commandqueue_dispatch_overrides->SetMarker(ctx, &args, _original);
    } else {
        _original(args._self, args.Metadata, args.pData, args.Size);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_ID3D12CommandQueue_SetMarker_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}

/*
 * ID3D12CommandQueue::BeginEvent
 */

struct npt_command_ID3D12CommandQueue_BeginEvent {
    void *_self;
    UINT Metadata;
    const void * pData;
    UINT Size;
};

static inline void
npt_decode_ID3D12CommandQueue_BeginEvent_args_temp(struct npt_cs_decoder *dec,
                                                   struct npt_command_ID3D12CommandQueue_BeginEvent *args)
{
    /* Decode input parameters from the wire */
    npt_decode_UINT(dec, &args->Metadata);
    {
        const uint64_t _blob_size = npt_decode_array_count_unchecked(dec);
        if (_blob_size) {
            args->pData = npt_cs_decoder_alloc_temp(dec, _blob_size);
            if (!args->pData) return;
            npt_decode_blob_array(dec, (void *)args->pData, _blob_size);
        } else {
            args->pData = NULL;
        }
    }
    npt_decode_UINT(dec, &args->Size);
    /* Allocate temp storage for output-only parameters */



}

static inline void
npt_replace_ID3D12CommandQueue_BeginEvent_args_handle(struct npt_dispatch_context *ctx, struct npt_command_ID3D12CommandQueue_BeginEvent *args)
{
}

static inline void
npt_encode_ID3D12CommandQueue_BeginEvent_reply(struct npt_cs_encoder *enc,
                                               const struct npt_command_ID3D12CommandQueue_BeginEvent *args)
{
    struct npt_reply_header _reply = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12CommandQueue,
                                 NPT_METHOD_ID3D12CommandQueue_BeginEvent),
        .cmd_return = 0,
    };
    npt_cs_encoder_write(enc, sizeof(_reply), &_reply, sizeof(_reply));
}

static inline void
npt_dispatch_ID3D12CommandQueue_BeginEvent(struct npt_dispatch_context *ctx,
                                           uint32_t cmd_flags,
                                           uint64_t object_id)
{
    struct npt_command_ID3D12CommandQueue_BeginEvent args;
    memset(&args, 0, sizeof(args));

    npt_decode_ID3D12CommandQueue_BeginEvent_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_ID3D12COMMANDQUEUE);
    if (!args._self) {
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_ID3D12CommandQueue_BeginEvent_args_handle(ctx, &args);

    PFN_ID3D12CommandQueue_BeginEvent _original = NPT_COM_VTBL_FUNC(
        PFN_ID3D12CommandQueue_BeginEvent, npt_com_vtable(args._self),
        NPT_VTBL_ID3D12CommandQueue_BeginEvent);

    if (ctx->id3d12commandqueue_dispatch_overrides && ctx->id3d12commandqueue_dispatch_overrides->BeginEvent) {
        ctx->id3d12commandqueue_dispatch_overrides->BeginEvent(ctx, &args, _original);
    } else {
        _original(args._self, args.Metadata, args.pData, args.Size);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_ID3D12CommandQueue_BeginEvent_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}

/*
 * ID3D12CommandQueue::EndEvent
 */

struct npt_command_ID3D12CommandQueue_EndEvent {
    void *_self;
};

static inline void
npt_decode_ID3D12CommandQueue_EndEvent_args_temp(struct npt_cs_decoder *dec,
                                                 struct npt_command_ID3D12CommandQueue_EndEvent *args)
{
    /* Decode input parameters from the wire */
    /* Allocate temp storage for output-only parameters */
}

static inline void
npt_replace_ID3D12CommandQueue_EndEvent_args_handle(struct npt_dispatch_context *ctx, struct npt_command_ID3D12CommandQueue_EndEvent *args)
{
}

static inline void
npt_encode_ID3D12CommandQueue_EndEvent_reply(struct npt_cs_encoder *enc,
                                             const struct npt_command_ID3D12CommandQueue_EndEvent *args)
{
    struct npt_reply_header _reply = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12CommandQueue,
                                 NPT_METHOD_ID3D12CommandQueue_EndEvent),
        .cmd_return = 0,
    };
    npt_cs_encoder_write(enc, sizeof(_reply), &_reply, sizeof(_reply));
}

static inline void
npt_dispatch_ID3D12CommandQueue_EndEvent(struct npt_dispatch_context *ctx,
                                         uint32_t cmd_flags,
                                         uint64_t object_id)
{
    struct npt_command_ID3D12CommandQueue_EndEvent args;
    memset(&args, 0, sizeof(args));

    npt_decode_ID3D12CommandQueue_EndEvent_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_ID3D12COMMANDQUEUE);
    if (!args._self) {
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_ID3D12CommandQueue_EndEvent_args_handle(ctx, &args);

    PFN_ID3D12CommandQueue_EndEvent _original = NPT_COM_VTBL_FUNC(
        PFN_ID3D12CommandQueue_EndEvent, npt_com_vtable(args._self),
        NPT_VTBL_ID3D12CommandQueue_EndEvent);

    if (ctx->id3d12commandqueue_dispatch_overrides && ctx->id3d12commandqueue_dispatch_overrides->EndEvent) {
        ctx->id3d12commandqueue_dispatch_overrides->EndEvent(ctx, &args, _original);
    } else {
        _original(args._self);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_ID3D12CommandQueue_EndEvent_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}

/*
 * ID3D12CommandQueue::Signal
 */

struct npt_command_ID3D12CommandQueue_Signal {
    void *_self;
    ID3D12Fence * pFence;
    UINT64 Value;
    HRESULT ret;
};

static inline void
npt_decode_ID3D12CommandQueue_Signal_args_temp(struct npt_cs_decoder *dec,
                                               struct npt_command_ID3D12CommandQueue_Signal *args)
{
    /* Decode input parameters from the wire */
    {
        npt_object_id _id;
        npt_decode_uint64_t(dec, &_id);
        args->pFence = (ID3D12Fence *)npt_object_from_id(_id);
    }
    npt_decode_UINT64(dec, &args->Value);
    /* Allocate temp storage for output-only parameters */


}

static inline void
npt_replace_ID3D12CommandQueue_Signal_args_handle(struct npt_dispatch_context *ctx, struct npt_command_ID3D12CommandQueue_Signal *args)
{
    args->pFence = npt_cs_handle_lookup(ctx, (npt_object_id)(uintptr_t)args->pFence, NPT_OBJECT_TYPE_ID3D12FENCE);
}

static inline void
npt_encode_ID3D12CommandQueue_Signal_reply(struct npt_cs_encoder *enc,
                                           const struct npt_command_ID3D12CommandQueue_Signal *args)
{
    struct npt_reply_header _reply = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12CommandQueue,
                                 NPT_METHOD_ID3D12CommandQueue_Signal),
        .cmd_return = (uint32_t)args->ret,
    };
    npt_cs_encoder_write(enc, sizeof(_reply), &_reply, sizeof(_reply));
}

static inline void
npt_dispatch_ID3D12CommandQueue_Signal(struct npt_dispatch_context *ctx,
                                       uint32_t cmd_flags,
                                       uint64_t object_id)
{
    struct npt_command_ID3D12CommandQueue_Signal args;
    memset(&args, 0, sizeof(args));

    npt_decode_ID3D12CommandQueue_Signal_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_ID3D12COMMANDQUEUE);
    if (!args._self) {
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_ID3D12CommandQueue_Signal_args_handle(ctx, &args);

    PFN_ID3D12CommandQueue_Signal _original = NPT_COM_VTBL_FUNC(
        PFN_ID3D12CommandQueue_Signal, npt_com_vtable(args._self),
        NPT_VTBL_ID3D12CommandQueue_Signal);

    if (ctx->id3d12commandqueue_dispatch_overrides && ctx->id3d12commandqueue_dispatch_overrides->Signal) {
        args.ret = ctx->id3d12commandqueue_dispatch_overrides->Signal(ctx, &args, _original);
    } else {
        args.ret = _original(args._self, args.pFence, args.Value);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_ID3D12CommandQueue_Signal_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}

/*
 * ID3D12CommandQueue::Wait
 */

struct npt_command_ID3D12CommandQueue_Wait {
    void *_self;
    ID3D12Fence * pFence;
    UINT64 Value;
    HRESULT ret;
};

static inline void
npt_decode_ID3D12CommandQueue_Wait_args_temp(struct npt_cs_decoder *dec,
                                             struct npt_command_ID3D12CommandQueue_Wait *args)
{
    /* Decode input parameters from the wire */
    {
        npt_object_id _id;
        npt_decode_uint64_t(dec, &_id);
        args->pFence = (ID3D12Fence *)npt_object_from_id(_id);
    }
    npt_decode_UINT64(dec, &args->Value);
    /* Allocate temp storage for output-only parameters */


}

static inline void
npt_replace_ID3D12CommandQueue_Wait_args_handle(struct npt_dispatch_context *ctx, struct npt_command_ID3D12CommandQueue_Wait *args)
{
    args->pFence = npt_cs_handle_lookup(ctx, (npt_object_id)(uintptr_t)args->pFence, NPT_OBJECT_TYPE_ID3D12FENCE);
}

static inline void
npt_encode_ID3D12CommandQueue_Wait_reply(struct npt_cs_encoder *enc,
                                         const struct npt_command_ID3D12CommandQueue_Wait *args)
{
    struct npt_reply_header _reply = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12CommandQueue,
                                 NPT_METHOD_ID3D12CommandQueue_Wait),
        .cmd_return = (uint32_t)args->ret,
    };
    npt_cs_encoder_write(enc, sizeof(_reply), &_reply, sizeof(_reply));
}

static inline void
npt_dispatch_ID3D12CommandQueue_Wait(struct npt_dispatch_context *ctx,
                                     uint32_t cmd_flags,
                                     uint64_t object_id)
{
    struct npt_command_ID3D12CommandQueue_Wait args;
    memset(&args, 0, sizeof(args));

    npt_decode_ID3D12CommandQueue_Wait_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_ID3D12COMMANDQUEUE);
    if (!args._self) {
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_ID3D12CommandQueue_Wait_args_handle(ctx, &args);

    PFN_ID3D12CommandQueue_Wait _original = NPT_COM_VTBL_FUNC(
        PFN_ID3D12CommandQueue_Wait, npt_com_vtable(args._self),
        NPT_VTBL_ID3D12CommandQueue_Wait);

    if (ctx->id3d12commandqueue_dispatch_overrides && ctx->id3d12commandqueue_dispatch_overrides->Wait) {
        args.ret = ctx->id3d12commandqueue_dispatch_overrides->Wait(ctx, &args, _original);
    } else {
        args.ret = _original(args._self, args.pFence, args.Value);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_ID3D12CommandQueue_Wait_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}

/*
 * ID3D12CommandQueue::GetTimestampFrequency
 */

struct npt_command_ID3D12CommandQueue_GetTimestampFrequency {
    void *_self;
    UINT64 * pFrequency;
    HRESULT ret;
};

static inline void
npt_decode_ID3D12CommandQueue_GetTimestampFrequency_args_temp(struct npt_cs_decoder *dec,
                                                              struct npt_command_ID3D12CommandQueue_GetTimestampFrequency *args)
{
    /* Decode input parameters from the wire */

    /* Allocate temp storage for output-only parameters */
    args->pFrequency = npt_cs_decoder_alloc_temp(dec, sizeof(UINT64));
    if (!args->pFrequency) return;
    memset(args->pFrequency, 0, sizeof(UINT64));
}

static inline void
npt_replace_ID3D12CommandQueue_GetTimestampFrequency_args_handle(struct npt_dispatch_context *ctx, struct npt_command_ID3D12CommandQueue_GetTimestampFrequency *args)
{
}

static inline void
npt_encode_ID3D12CommandQueue_GetTimestampFrequency_reply(struct npt_cs_encoder *enc,
                                                          const struct npt_command_ID3D12CommandQueue_GetTimestampFrequency *args)
{
    struct npt_reply_header _reply = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12CommandQueue,
                                 NPT_METHOD_ID3D12CommandQueue_GetTimestampFrequency),
        .cmd_return = (uint32_t)args->ret,
    };
    npt_cs_encoder_write(enc, sizeof(_reply), &_reply, sizeof(_reply));
    if (npt_encode_simple_pointer(enc, args->pFrequency))
        npt_encode_UINT64(enc, args->pFrequency);
}

static inline void
npt_dispatch_ID3D12CommandQueue_GetTimestampFrequency(struct npt_dispatch_context *ctx,
                                                      uint32_t cmd_flags,
                                                      uint64_t object_id)
{
    struct npt_command_ID3D12CommandQueue_GetTimestampFrequency args;
    memset(&args, 0, sizeof(args));

    npt_decode_ID3D12CommandQueue_GetTimestampFrequency_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_ID3D12COMMANDQUEUE);
    if (!args._self) {
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_ID3D12CommandQueue_GetTimestampFrequency_args_handle(ctx, &args);

    PFN_ID3D12CommandQueue_GetTimestampFrequency _original = NPT_COM_VTBL_FUNC(
        PFN_ID3D12CommandQueue_GetTimestampFrequency, npt_com_vtable(args._self),
        NPT_VTBL_ID3D12CommandQueue_GetTimestampFrequency);

    if (ctx->id3d12commandqueue_dispatch_overrides && ctx->id3d12commandqueue_dispatch_overrides->GetTimestampFrequency) {
        args.ret = ctx->id3d12commandqueue_dispatch_overrides->GetTimestampFrequency(ctx, &args, _original);
    } else {
        args.ret = _original(args._self, args.pFrequency);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_ID3D12CommandQueue_GetTimestampFrequency_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}

/*
 * ID3D12CommandQueue::GetClockCalibration
 */

struct npt_command_ID3D12CommandQueue_GetClockCalibration {
    void *_self;
    UINT64 * pGpuTimestamp;
    UINT64 * pCpuTimestamp;
    HRESULT ret;
};

static inline void
npt_decode_ID3D12CommandQueue_GetClockCalibration_args_temp(struct npt_cs_decoder *dec,
                                                            struct npt_command_ID3D12CommandQueue_GetClockCalibration *args)
{
    /* Decode input parameters from the wire */


    /* Allocate temp storage for output-only parameters */
    args->pGpuTimestamp = npt_cs_decoder_alloc_temp(dec, sizeof(UINT64));
    if (!args->pGpuTimestamp) return;
    memset(args->pGpuTimestamp, 0, sizeof(UINT64));
    args->pCpuTimestamp = npt_cs_decoder_alloc_temp(dec, sizeof(UINT64));
    if (!args->pCpuTimestamp) return;
    memset(args->pCpuTimestamp, 0, sizeof(UINT64));
}

static inline void
npt_replace_ID3D12CommandQueue_GetClockCalibration_args_handle(struct npt_dispatch_context *ctx, struct npt_command_ID3D12CommandQueue_GetClockCalibration *args)
{
}

static inline void
npt_encode_ID3D12CommandQueue_GetClockCalibration_reply(struct npt_cs_encoder *enc,
                                                        const struct npt_command_ID3D12CommandQueue_GetClockCalibration *args)
{
    struct npt_reply_header _reply = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12CommandQueue,
                                 NPT_METHOD_ID3D12CommandQueue_GetClockCalibration),
        .cmd_return = (uint32_t)args->ret,
    };
    npt_cs_encoder_write(enc, sizeof(_reply), &_reply, sizeof(_reply));
    if (npt_encode_simple_pointer(enc, args->pGpuTimestamp))
        npt_encode_UINT64(enc, args->pGpuTimestamp);
    if (npt_encode_simple_pointer(enc, args->pCpuTimestamp))
        npt_encode_UINT64(enc, args->pCpuTimestamp);
}

static inline void
npt_dispatch_ID3D12CommandQueue_GetClockCalibration(struct npt_dispatch_context *ctx,
                                                    uint32_t cmd_flags,
                                                    uint64_t object_id)
{
    struct npt_command_ID3D12CommandQueue_GetClockCalibration args;
    memset(&args, 0, sizeof(args));

    npt_decode_ID3D12CommandQueue_GetClockCalibration_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_ID3D12COMMANDQUEUE);
    if (!args._self) {
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_ID3D12CommandQueue_GetClockCalibration_args_handle(ctx, &args);

    PFN_ID3D12CommandQueue_GetClockCalibration _original = NPT_COM_VTBL_FUNC(
        PFN_ID3D12CommandQueue_GetClockCalibration, npt_com_vtable(args._self),
        NPT_VTBL_ID3D12CommandQueue_GetClockCalibration);

    if (ctx->id3d12commandqueue_dispatch_overrides && ctx->id3d12commandqueue_dispatch_overrides->GetClockCalibration) {
        args.ret = ctx->id3d12commandqueue_dispatch_overrides->GetClockCalibration(ctx, &args, _original);
    } else {
        args.ret = _original(args._self, args.pGpuTimestamp, args.pCpuTimestamp);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_ID3D12CommandQueue_GetClockCalibration_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}

/*
 * ID3D12CommandQueue::GetDesc
 */

struct npt_command_ID3D12CommandQueue_GetDesc {
    void *_self;
    D3D12_COMMAND_QUEUE_DESC ret;
};

static inline void
npt_decode_ID3D12CommandQueue_GetDesc_args_temp(struct npt_cs_decoder *dec,
                                                struct npt_command_ID3D12CommandQueue_GetDesc *args)
{
    /* Decode input parameters from the wire */
    /* Allocate temp storage for output-only parameters */
}

static inline void
npt_replace_ID3D12CommandQueue_GetDesc_args_handle(struct npt_dispatch_context *ctx, struct npt_command_ID3D12CommandQueue_GetDesc *args)
{
}

static inline void
npt_encode_ID3D12CommandQueue_GetDesc_reply(struct npt_cs_encoder *enc,
                                            const struct npt_command_ID3D12CommandQueue_GetDesc *args)
{
    struct npt_reply_header _reply = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12CommandQueue,
                                 NPT_METHOD_ID3D12CommandQueue_GetDesc),
        .cmd_return = 0,
    };
    npt_cs_encoder_write(enc, sizeof(_reply), &_reply, sizeof(_reply));
    npt_encode_D3D12_COMMAND_QUEUE_DESC(enc, &args->ret);
}

static inline void
npt_dispatch_ID3D12CommandQueue_GetDesc(struct npt_dispatch_context *ctx,
                                        uint32_t cmd_flags,
                                        uint64_t object_id)
{
    struct npt_command_ID3D12CommandQueue_GetDesc args;
    memset(&args, 0, sizeof(args));

    npt_decode_ID3D12CommandQueue_GetDesc_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_ID3D12COMMANDQUEUE);
    if (!args._self) {
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_ID3D12CommandQueue_GetDesc_args_handle(ctx, &args);

    PFN_ID3D12CommandQueue_GetDesc _original = NPT_COM_VTBL_FUNC(
        PFN_ID3D12CommandQueue_GetDesc, npt_com_vtable(args._self),
        NPT_VTBL_ID3D12CommandQueue_GetDesc);

    if (ctx->id3d12commandqueue_dispatch_overrides && ctx->id3d12commandqueue_dispatch_overrides->GetDesc) {
        args.ret = ctx->id3d12commandqueue_dispatch_overrides->GetDesc(ctx, &args, _original);
    } else {
        args.ret = _original(args._self);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_ID3D12CommandQueue_GetDesc_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}


#pragma GCC diagnostic pop

#endif /* NPT_PROTOCOL_HOST_ID3D12COMMANDQUEUE_H */
