/*
 * Copyright 2026 Turing Software LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * Generated by npt_protocol.py -- do not edit.
 *
 * Command structs and encode/decode for idxgikeyedmutex.
 */

#ifndef NPT_PROTOCOL_HOST_IDXGIKEYEDMUTEX_H
#define NPT_PROTOCOL_HOST_IDXGIKEYEDMUTEX_H

#include "npt_protocol_host_structs.h"
#include "npt_protocol_host_dispatch_types.h"

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-parameter"
#pragma GCC diagnostic ignored "-Wpointer-arith"

/*
 * IDXGIKeyedMutex::AcquireSync
 */

struct npt_command_IDXGIKeyedMutex_AcquireSync {
    void *_self;
    UINT64 Key;
    DWORD dwMilliseconds;
    HRESULT ret;
};

static inline void
npt_decode_IDXGIKeyedMutex_AcquireSync_args_temp(struct npt_cs_decoder *dec,
                                                 struct npt_command_IDXGIKeyedMutex_AcquireSync *args)
{
    /* Decode input parameters from the wire */
    npt_decode_UINT64(dec, &args->Key);
    npt_decode_DWORD(dec, &args->dwMilliseconds);
    /* Allocate temp storage for output-only parameters */


}

static inline void
npt_replace_IDXGIKeyedMutex_AcquireSync_args_handle(struct npt_dispatch_context *ctx, struct npt_command_IDXGIKeyedMutex_AcquireSync *args)
{
}

static inline void
npt_encode_IDXGIKeyedMutex_AcquireSync_reply(struct npt_cs_encoder *enc,
                                             const struct npt_command_IDXGIKeyedMutex_AcquireSync *args)
{
    struct npt_reply_header _reply = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_IDXGIKeyedMutex,
                                 NPT_METHOD_IDXGIKeyedMutex_AcquireSync),
        .cmd_return = (uint32_t)args->ret,
    };
    npt_cs_encoder_write(enc, sizeof(_reply), &_reply, sizeof(_reply));
}

static inline void
npt_dispatch_IDXGIKeyedMutex_AcquireSync(struct npt_dispatch_context *ctx,
                                         uint32_t cmd_flags,
                                         uint64_t object_id)
{
    struct npt_command_IDXGIKeyedMutex_AcquireSync args;
    memset(&args, 0, sizeof(args));

    npt_decode_IDXGIKeyedMutex_AcquireSync_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_IDXGIKEYEDMUTEX);
    if (!args._self) {
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_IDXGIKeyedMutex_AcquireSync_args_handle(ctx, &args);

    PFN_IDXGIKeyedMutex_AcquireSync _original = NPT_COM_VTBL_FUNC(
        PFN_IDXGIKeyedMutex_AcquireSync, npt_com_vtable(args._self),
        NPT_VTBL_IDXGIKeyedMutex_AcquireSync);

    if (ctx->idxgikeyedmutex_dispatch_overrides && ctx->idxgikeyedmutex_dispatch_overrides->AcquireSync) {
        args.ret = ctx->idxgikeyedmutex_dispatch_overrides->AcquireSync(ctx, &args, _original);
    } else {
        args.ret = _original(args._self, args.Key, args.dwMilliseconds);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_IDXGIKeyedMutex_AcquireSync_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}

/*
 * IDXGIKeyedMutex::ReleaseSync
 */

struct npt_command_IDXGIKeyedMutex_ReleaseSync {
    void *_self;
    UINT64 Key;
    HRESULT ret;
};

static inline void
npt_decode_IDXGIKeyedMutex_ReleaseSync_args_temp(struct npt_cs_decoder *dec,
                                                 struct npt_command_IDXGIKeyedMutex_ReleaseSync *args)
{
    /* Decode input parameters from the wire */
    npt_decode_UINT64(dec, &args->Key);
    /* Allocate temp storage for output-only parameters */

}

static inline void
npt_replace_IDXGIKeyedMutex_ReleaseSync_args_handle(struct npt_dispatch_context *ctx, struct npt_command_IDXGIKeyedMutex_ReleaseSync *args)
{
}

static inline void
npt_encode_IDXGIKeyedMutex_ReleaseSync_reply(struct npt_cs_encoder *enc,
                                             const struct npt_command_IDXGIKeyedMutex_ReleaseSync *args)
{
    struct npt_reply_header _reply = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_IDXGIKeyedMutex,
                                 NPT_METHOD_IDXGIKeyedMutex_ReleaseSync),
        .cmd_return = (uint32_t)args->ret,
    };
    npt_cs_encoder_write(enc, sizeof(_reply), &_reply, sizeof(_reply));
}

static inline void
npt_dispatch_IDXGIKeyedMutex_ReleaseSync(struct npt_dispatch_context *ctx,
                                         uint32_t cmd_flags,
                                         uint64_t object_id)
{
    struct npt_command_IDXGIKeyedMutex_ReleaseSync args;
    memset(&args, 0, sizeof(args));

    npt_decode_IDXGIKeyedMutex_ReleaseSync_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_IDXGIKEYEDMUTEX);
    if (!args._self) {
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_IDXGIKeyedMutex_ReleaseSync_args_handle(ctx, &args);

    PFN_IDXGIKeyedMutex_ReleaseSync _original = NPT_COM_VTBL_FUNC(
        PFN_IDXGIKeyedMutex_ReleaseSync, npt_com_vtable(args._self),
        NPT_VTBL_IDXGIKeyedMutex_ReleaseSync);

    if (ctx->idxgikeyedmutex_dispatch_overrides && ctx->idxgikeyedmutex_dispatch_overrides->ReleaseSync) {
        args.ret = ctx->idxgikeyedmutex_dispatch_overrides->ReleaseSync(ctx, &args, _original);
    } else {
        args.ret = _original(args._self, args.Key);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_IDXGIKeyedMutex_ReleaseSync_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}


#pragma GCC diagnostic pop

#endif /* NPT_PROTOCOL_HOST_IDXGIKEYEDMUTEX_H */
