/*
 * Copyright 2026 Turing Software LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * Generated by npt_protocol.py -- do not edit.
 *
 * Command structs and encode/decode for id3d12rootsignaturedeserializer.
 */

#ifndef NPT_PROTOCOL_HOST_ID3D12ROOTSIGNATUREDESERIALIZER_H
#define NPT_PROTOCOL_HOST_ID3D12ROOTSIGNATUREDESERIALIZER_H

#include "npt_protocol_host_structs.h"
#include "npt_protocol_host_dispatch_types.h"

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-parameter"
#pragma GCC diagnostic ignored "-Wpointer-arith"

/*
 * ID3D12RootSignatureDeserializer::GetRootSignatureDesc
 */

struct npt_command_ID3D12RootSignatureDeserializer_GetRootSignatureDesc {
    void *_self;
    D3D12_ROOT_SIGNATURE_DESC ret;
};

static inline void
npt_decode_ID3D12RootSignatureDeserializer_GetRootSignatureDesc_args_temp(struct npt_cs_decoder *dec,
                                                                          struct npt_command_ID3D12RootSignatureDeserializer_GetRootSignatureDesc *args)
{
    /* Decode input parameters from the wire */
    /* Allocate temp storage for output-only parameters */
}

static inline void
npt_replace_ID3D12RootSignatureDeserializer_GetRootSignatureDesc_args_handle(struct npt_dispatch_context *ctx, struct npt_command_ID3D12RootSignatureDeserializer_GetRootSignatureDesc *args)
{
}

static inline void
npt_encode_ID3D12RootSignatureDeserializer_GetRootSignatureDesc_reply(struct npt_cs_encoder *enc,
                                                                      const struct npt_command_ID3D12RootSignatureDeserializer_GetRootSignatureDesc *args)
{
    /* ID3D12RootSignatureDeserializer::GetRootSignatureDesc: reply contains a type with
     * runtime-unbounded wire size (e.g. DRED chain pointers, root-
     * signature parameter arrays).  A pre-reserved fixed-size reply
     * slot cannot represent this without truncating the host data, so
     * the guest gets a clean reply-mismatch via the encoder fatal
     * flag rather than a corrupted stream. */
    npt_cs_encoder_set_fatal(enc);
    return;
}

static inline void
npt_dispatch_ID3D12RootSignatureDeserializer_GetRootSignatureDesc(struct npt_dispatch_context *ctx,
                                                                  uint32_t cmd_flags,
                                                                  uint64_t object_id)
{
    struct npt_command_ID3D12RootSignatureDeserializer_GetRootSignatureDesc args;
    memset(&args, 0, sizeof(args));

    npt_decode_ID3D12RootSignatureDeserializer_GetRootSignatureDesc_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_ID3D12ROOTSIGNATUREDESERIALIZER);
    if (!args._self) {
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_ID3D12RootSignatureDeserializer_GetRootSignatureDesc_args_handle(ctx, &args);

    PFN_ID3D12RootSignatureDeserializer_GetRootSignatureDesc _original = NPT_COM_VTBL_FUNC(
        PFN_ID3D12RootSignatureDeserializer_GetRootSignatureDesc, npt_com_vtable(args._self),
        NPT_VTBL_ID3D12RootSignatureDeserializer_GetRootSignatureDesc);

    if (ctx->id3d12rootsignaturedeserializer_dispatch_overrides && ctx->id3d12rootsignaturedeserializer_dispatch_overrides->GetRootSignatureDesc) {
        args.ret = ctx->id3d12rootsignaturedeserializer_dispatch_overrides->GetRootSignatureDesc(ctx, &args, _original);
    } else {
        args.ret = _original(args._self);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_ID3D12RootSignatureDeserializer_GetRootSignatureDesc_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}


#pragma GCC diagnostic pop

#endif /* NPT_PROTOCOL_HOST_ID3D12ROOTSIGNATUREDESERIALIZER_H */
