/*
 * Copyright 2026 Turing Software LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * Generated by npt_protocol.py -- do not edit.
 *
 * Command structs and encode/decode for id3d11asynchronous.
 */

#ifndef NPT_PROTOCOL_HOST_ID3D11ASYNCHRONOUS_H
#define NPT_PROTOCOL_HOST_ID3D11ASYNCHRONOUS_H

#include "npt_protocol_host_structs.h"
#include "npt_protocol_host_dispatch_types.h"

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-parameter"
#pragma GCC diagnostic ignored "-Wpointer-arith"

/*
 * ID3D11Asynchronous::GetDataSize
 */

struct npt_command_ID3D11Asynchronous_GetDataSize {
    void *_self;
    UINT ret;
};

static inline void
npt_decode_ID3D11Asynchronous_GetDataSize_args_temp(struct npt_cs_decoder *dec,
                                                    struct npt_command_ID3D11Asynchronous_GetDataSize *args)
{
    /* Decode input parameters from the wire */
    /* Allocate temp storage for output-only parameters */
}

static inline void
npt_replace_ID3D11Asynchronous_GetDataSize_args_handle(struct npt_dispatch_context *ctx, struct npt_command_ID3D11Asynchronous_GetDataSize *args)
{
}

static inline void
npt_encode_ID3D11Asynchronous_GetDataSize_reply(struct npt_cs_encoder *enc,
                                                const struct npt_command_ID3D11Asynchronous_GetDataSize *args)
{
    struct npt_reply_header _reply = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D11Asynchronous,
                                 NPT_METHOD_ID3D11Asynchronous_GetDataSize),
        .cmd_return = (uint32_t)args->ret,
    };
    npt_cs_encoder_write(enc, sizeof(_reply), &_reply, sizeof(_reply));
}

static inline void
npt_dispatch_ID3D11Asynchronous_GetDataSize(struct npt_dispatch_context *ctx,
                                            uint32_t cmd_flags,
                                            uint64_t object_id)
{
    struct npt_command_ID3D11Asynchronous_GetDataSize args;
    memset(&args, 0, sizeof(args));

    npt_decode_ID3D11Asynchronous_GetDataSize_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_ID3D11ASYNCHRONOUS);
    if (!args._self) {
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_ID3D11Asynchronous_GetDataSize_args_handle(ctx, &args);

    PFN_ID3D11Asynchronous_GetDataSize _original = NPT_COM_VTBL_FUNC(
        PFN_ID3D11Asynchronous_GetDataSize, npt_com_vtable(args._self),
        NPT_VTBL_ID3D11Asynchronous_GetDataSize);

    if (ctx->id3d11asynchronous_dispatch_overrides && ctx->id3d11asynchronous_dispatch_overrides->GetDataSize) {
        args.ret = ctx->id3d11asynchronous_dispatch_overrides->GetDataSize(ctx, &args, _original);
    } else {
        args.ret = _original(args._self);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_ID3D11Asynchronous_GetDataSize_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}


#pragma GCC diagnostic pop

#endif /* NPT_PROTOCOL_HOST_ID3D11ASYNCHRONOUS_H */
