/*
 * Copyright 2026 Turing Software LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * Generated by npt_protocol.py -- do not edit.
 *
 * Command structs and encode/decode for id3d12heap.
 */

#ifndef NPT_PROTOCOL_HOST_ID3D12HEAP_H
#define NPT_PROTOCOL_HOST_ID3D12HEAP_H

#include "npt_protocol_host_structs.h"
#include "npt_protocol_host_dispatch_types.h"

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-parameter"
#pragma GCC diagnostic ignored "-Wpointer-arith"

/*
 * ID3D12Heap::GetDesc
 */

struct npt_command_ID3D12Heap_GetDesc {
    void *_self;
    D3D12_HEAP_DESC ret;
};

static inline void
npt_decode_ID3D12Heap_GetDesc_args_temp(struct npt_cs_decoder *dec,
                                        struct npt_command_ID3D12Heap_GetDesc *args)
{
    /* Decode input parameters from the wire */
    /* Allocate temp storage for output-only parameters */
}

static inline void
npt_replace_ID3D12Heap_GetDesc_args_handle(struct npt_dispatch_context *ctx, struct npt_command_ID3D12Heap_GetDesc *args)
{
}

static inline void
npt_encode_ID3D12Heap_GetDesc_reply(struct npt_cs_encoder *enc,
                                    const struct npt_command_ID3D12Heap_GetDesc *args)
{
    struct npt_reply_header _reply = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12Heap,
                                 NPT_METHOD_ID3D12Heap_GetDesc),
        .cmd_return = 0,
    };
    npt_cs_encoder_write(enc, sizeof(_reply), &_reply, sizeof(_reply));
    npt_encode_D3D12_HEAP_DESC(enc, &args->ret);
}

static inline void
npt_dispatch_ID3D12Heap_GetDesc(struct npt_dispatch_context *ctx,
                                uint32_t cmd_flags,
                                uint64_t object_id)
{
    struct npt_command_ID3D12Heap_GetDesc args;
    memset(&args, 0, sizeof(args));

    npt_decode_ID3D12Heap_GetDesc_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_ID3D12HEAP);
    if (!args._self) {
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_ID3D12Heap_GetDesc_args_handle(ctx, &args);

    PFN_ID3D12Heap_GetDesc _original = NPT_COM_VTBL_FUNC(
        PFN_ID3D12Heap_GetDesc, npt_com_vtable(args._self),
        NPT_VTBL_ID3D12Heap_GetDesc);

    if (ctx->id3d12heap_dispatch_overrides && ctx->id3d12heap_dispatch_overrides->GetDesc) {
        args.ret = ctx->id3d12heap_dispatch_overrides->GetDesc(ctx, &args, _original);
    } else {
        args.ret = _original(args._self);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_ID3D12Heap_GetDesc_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}

/*
 * ID3D12Heap1::GetProtectedResourceSession
 */

struct npt_command_ID3D12Heap1_GetProtectedResourceSession {
    void *_self;
    const IID * riid;
    void ** ppProtectedSession;
    /* Shadow: the guest-allocated id for ppProtectedSession arrives in the command
     * body (no reply round-trip).  The post-dispatch register pass reads
     * this field and inserts {_guest_id_ppProtectedSession -> *ppProtectedSession} in the
     * context object table. */
    uint64_t _guest_id_ppProtectedSession;
    HRESULT ret;
};

static inline void
npt_decode_ID3D12Heap1_GetProtectedResourceSession_args_temp(struct npt_cs_decoder *dec,
                                                             struct npt_command_ID3D12Heap1_GetProtectedResourceSession *args)
{
    /* Decode input parameters from the wire */
    if (npt_decode_simple_pointer(dec)) {
        args->riid = npt_cs_decoder_alloc_temp(dec, sizeof(IID));
        if (!args->riid) return;
        npt_decode_IID(dec, (IID *)args->riid);
    } else {
        args->riid = NULL;
        npt_cs_decoder_set_fatal(dec); /* non-optional pointer is NULL */
    }
    {
        uint64_t _gid;
        npt_decode_uint64_t(dec, &_gid);
        args->_guest_id_ppProtectedSession = _gid;
        args->ppProtectedSession = npt_cs_decoder_alloc_temp(dec, sizeof(void *));
        if (!args->ppProtectedSession) return;
        *args->ppProtectedSession = NULL;
    }
    /* Allocate temp storage for output-only parameters */


}

static inline void
npt_replace_ID3D12Heap1_GetProtectedResourceSession_args_handle(struct npt_dispatch_context *ctx, struct npt_command_ID3D12Heap1_GetProtectedResourceSession *args)
{
}

static inline void
npt_encode_ID3D12Heap1_GetProtectedResourceSession_reply(struct npt_cs_encoder *enc,
                                                         const struct npt_command_ID3D12Heap1_GetProtectedResourceSession *args)
{
    struct npt_reply_header _reply = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12Heap1,
                                 NPT_METHOD_ID3D12Heap1_GetProtectedResourceSession),
        .cmd_return = (uint32_t)args->ret,
    };
    npt_cs_encoder_write(enc, sizeof(_reply), &_reply, sizeof(_reply));
/* skip args->ppProtectedSession (guest-allocated id, registered host-side; not in reply) */
}

static inline void
npt_dispatch_ID3D12Heap1_GetProtectedResourceSession(struct npt_dispatch_context *ctx,
                                                     uint32_t cmd_flags,
                                                     uint64_t object_id)
{
    struct npt_command_ID3D12Heap1_GetProtectedResourceSession args;
    memset(&args, 0, sizeof(args));

    npt_decode_ID3D12Heap1_GetProtectedResourceSession_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_ID3D12HEAP1);
    if (!args._self) {
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_ID3D12Heap1_GetProtectedResourceSession_args_handle(ctx, &args);

    PFN_ID3D12Heap1_GetProtectedResourceSession _original = NPT_COM_VTBL_FUNC(
        PFN_ID3D12Heap1_GetProtectedResourceSession, npt_com_vtable(args._self),
        NPT_VTBL_ID3D12Heap1_GetProtectedResourceSession);

    if (ctx->id3d12heap1_dispatch_overrides && ctx->id3d12heap1_dispatch_overrides->GetProtectedResourceSession) {
        args.ret = ctx->id3d12heap1_dispatch_overrides->GetProtectedResourceSession(ctx, &args, _original);
    } else {
        args.ret = _original(args._self, args.riid, args.ppProtectedSession);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */
    if (args.ppProtectedSession && *args.ppProtectedSession)
        npt_cs_handle_register_guest_id(ctx, args._guest_id_ppProtectedSession, *args.ppProtectedSession,
            npt_object_type_from_iid(args.riid));

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_ID3D12Heap1_GetProtectedResourceSession_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}


#pragma GCC diagnostic pop

#endif /* NPT_PROTOCOL_HOST_ID3D12HEAP_H */
