/*
 * Copyright 2026 Turing Software LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * Generated by npt_protocol.py -- do not edit.
 *
 * Command structs and encode/decode for id3d12virtualizationguestdevice.
 */

#ifndef NPT_PROTOCOL_HOST_ID3D12VIRTUALIZATIONGUESTDEVICE_H
#define NPT_PROTOCOL_HOST_ID3D12VIRTUALIZATIONGUESTDEVICE_H

#include "npt_protocol_host_structs.h"
#include "npt_protocol_host_dispatch_types.h"

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-parameter"
#pragma GCC diagnostic ignored "-Wpointer-arith"

/*
 * ID3D12VirtualizationGuestDevice::ShareWithHost
 */

struct npt_command_ID3D12VirtualizationGuestDevice_ShareWithHost {
    void *_self;
    ID3D12DeviceChild * pObject;
    HANDLE * pHandle;
    HRESULT ret;
};

static inline void
npt_decode_ID3D12VirtualizationGuestDevice_ShareWithHost_args_temp(struct npt_cs_decoder *dec,
                                                                   struct npt_command_ID3D12VirtualizationGuestDevice_ShareWithHost *args)
{
    /* Decode input parameters from the wire */
    {
        npt_object_id _id;
        npt_decode_uint64_t(dec, &_id);
        args->pObject = (ID3D12DeviceChild *)npt_object_from_id(_id);
    }

    /* Allocate temp storage for output-only parameters */

    args->pHandle = npt_cs_decoder_alloc_temp(dec, sizeof(HANDLE));
    if (!args->pHandle) return;
    memset(args->pHandle, 0, sizeof(HANDLE));
}

static inline void
npt_replace_ID3D12VirtualizationGuestDevice_ShareWithHost_args_handle(struct npt_dispatch_context *ctx, struct npt_command_ID3D12VirtualizationGuestDevice_ShareWithHost *args)
{
    args->pObject = npt_cs_handle_lookup(ctx, (npt_object_id)(uintptr_t)args->pObject, NPT_OBJECT_TYPE_ID3D12DEVICECHILD);
}

static inline void
npt_encode_ID3D12VirtualizationGuestDevice_ShareWithHost_reply(struct npt_cs_encoder *enc,
                                                               const struct npt_command_ID3D12VirtualizationGuestDevice_ShareWithHost *args)
{
    struct npt_reply_header _reply = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12VirtualizationGuestDevice,
                                 NPT_METHOD_ID3D12VirtualizationGuestDevice_ShareWithHost),
        .cmd_return = (uint32_t)args->ret,
    };
    npt_cs_encoder_write(enc, sizeof(_reply), &_reply, sizeof(_reply));
    npt_encode_win32_handle(enc, npt_win32_handle_get_id((const void *)(uintptr_t)*args->pHandle));
}

static inline void
npt_dispatch_ID3D12VirtualizationGuestDevice_ShareWithHost(struct npt_dispatch_context *ctx,
                                                           uint32_t cmd_flags,
                                                           uint64_t object_id)
{
    struct npt_command_ID3D12VirtualizationGuestDevice_ShareWithHost args;
    memset(&args, 0, sizeof(args));

    npt_decode_ID3D12VirtualizationGuestDevice_ShareWithHost_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_ID3D12VIRTUALIZATIONGUESTDEVICE);
    if (!args._self) {
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_ID3D12VirtualizationGuestDevice_ShareWithHost_args_handle(ctx, &args);

    PFN_ID3D12VirtualizationGuestDevice_ShareWithHost _original = NPT_COM_VTBL_FUNC(
        PFN_ID3D12VirtualizationGuestDevice_ShareWithHost, npt_com_vtable(args._self),
        NPT_VTBL_ID3D12VirtualizationGuestDevice_ShareWithHost);

    if (ctx->id3d12virtualizationguestdevice_dispatch_overrides && ctx->id3d12virtualizationguestdevice_dispatch_overrides->ShareWithHost) {
        args.ret = ctx->id3d12virtualizationguestdevice_dispatch_overrides->ShareWithHost(ctx, &args, _original);
    } else {
        args.ret = _original(args._self, args.pObject, args.pHandle);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_ID3D12VirtualizationGuestDevice_ShareWithHost_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}

/*
 * ID3D12VirtualizationGuestDevice::CreateFenceFd
 */

struct npt_command_ID3D12VirtualizationGuestDevice_CreateFenceFd {
    void *_self;
    ID3D12Fence * pFence;
    UINT64 FenceValue;
    int * pFenceFd;
    HRESULT ret;
};

static inline void
npt_decode_ID3D12VirtualizationGuestDevice_CreateFenceFd_args_temp(struct npt_cs_decoder *dec,
                                                                   struct npt_command_ID3D12VirtualizationGuestDevice_CreateFenceFd *args)
{
    /* Decode input parameters from the wire */
    {
        npt_object_id _id;
        npt_decode_uint64_t(dec, &_id);
        args->pFence = (ID3D12Fence *)npt_object_from_id(_id);
    }
    npt_decode_UINT64(dec, &args->FenceValue);

    /* Allocate temp storage for output-only parameters */


    args->pFenceFd = npt_cs_decoder_alloc_temp(dec, sizeof(int));
    if (!args->pFenceFd) return;
    memset(args->pFenceFd, 0, sizeof(int));
}

static inline void
npt_replace_ID3D12VirtualizationGuestDevice_CreateFenceFd_args_handle(struct npt_dispatch_context *ctx, struct npt_command_ID3D12VirtualizationGuestDevice_CreateFenceFd *args)
{
    args->pFence = npt_cs_handle_lookup(ctx, (npt_object_id)(uintptr_t)args->pFence, NPT_OBJECT_TYPE_ID3D12FENCE);
}

static inline void
npt_encode_ID3D12VirtualizationGuestDevice_CreateFenceFd_reply(struct npt_cs_encoder *enc,
                                                               const struct npt_command_ID3D12VirtualizationGuestDevice_CreateFenceFd *args)
{
    struct npt_reply_header _reply = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12VirtualizationGuestDevice,
                                 NPT_METHOD_ID3D12VirtualizationGuestDevice_CreateFenceFd),
        .cmd_return = (uint32_t)args->ret,
    };
    npt_cs_encoder_write(enc, sizeof(_reply), &_reply, sizeof(_reply));
    if (npt_encode_simple_pointer(enc, args->pFenceFd))
        npt_encode_int(enc, args->pFenceFd);
}

static inline void
npt_dispatch_ID3D12VirtualizationGuestDevice_CreateFenceFd(struct npt_dispatch_context *ctx,
                                                           uint32_t cmd_flags,
                                                           uint64_t object_id)
{
    struct npt_command_ID3D12VirtualizationGuestDevice_CreateFenceFd args;
    memset(&args, 0, sizeof(args));

    npt_decode_ID3D12VirtualizationGuestDevice_CreateFenceFd_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_ID3D12VIRTUALIZATIONGUESTDEVICE);
    if (!args._self) {
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_ID3D12VirtualizationGuestDevice_CreateFenceFd_args_handle(ctx, &args);

    PFN_ID3D12VirtualizationGuestDevice_CreateFenceFd _original = NPT_COM_VTBL_FUNC(
        PFN_ID3D12VirtualizationGuestDevice_CreateFenceFd, npt_com_vtable(args._self),
        NPT_VTBL_ID3D12VirtualizationGuestDevice_CreateFenceFd);

    if (ctx->id3d12virtualizationguestdevice_dispatch_overrides && ctx->id3d12virtualizationguestdevice_dispatch_overrides->CreateFenceFd) {
        args.ret = ctx->id3d12virtualizationguestdevice_dispatch_overrides->CreateFenceFd(ctx, &args, _original);
    } else {
        args.ret = _original(args._self, args.pFence, args.FenceValue, args.pFenceFd);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_ID3D12VirtualizationGuestDevice_CreateFenceFd_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}


#pragma GCC diagnostic pop

#endif /* NPT_PROTOCOL_HOST_ID3D12VIRTUALIZATIONGUESTDEVICE_H */
