/*
 * Copyright 2026 Turing Software LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * Generated by npt_protocol.py -- do not edit.
 *
 * Command structs and encode/decode for id3ddevicecontextstate.
 */

#ifndef NPT_PROTOCOL_HOST_ID3DDEVICECONTEXTSTATE_H
#define NPT_PROTOCOL_HOST_ID3DDEVICECONTEXTSTATE_H

#include "npt_protocol_host_structs.h"
#include "npt_protocol_host_dispatch_types.h"

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-parameter"
#pragma GCC diagnostic ignored "-Wpointer-arith"


#pragma GCC diagnostic pop

#endif /* NPT_PROTOCOL_HOST_ID3DDEVICECONTEXTSTATE_H */
