/*
 * Copyright 2026 Turing Software LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * Generated by npt_protocol.py -- do not edit.
 *
 * Command structs and encode/decode for id3d12protectedresourcesession.
 */

#ifndef NPT_PROTOCOL_HOST_ID3D12PROTECTEDRESOURCESESSION_H
#define NPT_PROTOCOL_HOST_ID3D12PROTECTEDRESOURCESESSION_H

#include "npt_protocol_host_structs.h"
#include "npt_protocol_host_dispatch_types.h"

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-parameter"
#pragma GCC diagnostic ignored "-Wpointer-arith"

/*
 * ID3D12ProtectedResourceSession::GetDesc
 */

struct npt_command_ID3D12ProtectedResourceSession_GetDesc {
    void *_self;
    D3D12_PROTECTED_RESOURCE_SESSION_DESC ret;
};

static inline void
npt_decode_ID3D12ProtectedResourceSession_GetDesc_args_temp(struct npt_cs_decoder *dec,
                                                            struct npt_command_ID3D12ProtectedResourceSession_GetDesc *args)
{
    /* Decode input parameters from the wire */
    /* Allocate temp storage for output-only parameters */
}

static inline void
npt_replace_ID3D12ProtectedResourceSession_GetDesc_args_handle(struct npt_dispatch_context *ctx, struct npt_command_ID3D12ProtectedResourceSession_GetDesc *args)
{
}

static inline void
npt_encode_ID3D12ProtectedResourceSession_GetDesc_reply(struct npt_cs_encoder *enc,
                                                        const struct npt_command_ID3D12ProtectedResourceSession_GetDesc *args)
{
    struct npt_reply_header _reply = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12ProtectedResourceSession,
                                 NPT_METHOD_ID3D12ProtectedResourceSession_GetDesc),
        .cmd_return = 0,
    };
    npt_cs_encoder_write(enc, sizeof(_reply), &_reply, sizeof(_reply));
    npt_encode_D3D12_PROTECTED_RESOURCE_SESSION_DESC(enc, &args->ret);
}

static inline void
npt_dispatch_ID3D12ProtectedResourceSession_GetDesc(struct npt_dispatch_context *ctx,
                                                    uint32_t cmd_flags,
                                                    uint64_t object_id)
{
    struct npt_command_ID3D12ProtectedResourceSession_GetDesc args;
    memset(&args, 0, sizeof(args));

    npt_decode_ID3D12ProtectedResourceSession_GetDesc_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_ID3D12PROTECTEDRESOURCESESSION);
    if (!args._self) {
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_ID3D12ProtectedResourceSession_GetDesc_args_handle(ctx, &args);

    PFN_ID3D12ProtectedResourceSession_GetDesc _original = NPT_COM_VTBL_FUNC(
        PFN_ID3D12ProtectedResourceSession_GetDesc, npt_com_vtable(args._self),
        NPT_VTBL_ID3D12ProtectedResourceSession_GetDesc);

    if (ctx->id3d12protectedresourcesession_dispatch_overrides && ctx->id3d12protectedresourcesession_dispatch_overrides->GetDesc) {
        args.ret = ctx->id3d12protectedresourcesession_dispatch_overrides->GetDesc(ctx, &args, _original);
    } else {
        args.ret = _original(args._self);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_ID3D12ProtectedResourceSession_GetDesc_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}

/*
 * ID3D12ProtectedResourceSession1::GetDesc1
 */

struct npt_command_ID3D12ProtectedResourceSession1_GetDesc1 {
    void *_self;
    D3D12_PROTECTED_RESOURCE_SESSION_DESC1 ret;
};

static inline void
npt_decode_ID3D12ProtectedResourceSession1_GetDesc1_args_temp(struct npt_cs_decoder *dec,
                                                              struct npt_command_ID3D12ProtectedResourceSession1_GetDesc1 *args)
{
    /* Decode input parameters from the wire */
    /* Allocate temp storage for output-only parameters */
}

static inline void
npt_replace_ID3D12ProtectedResourceSession1_GetDesc1_args_handle(struct npt_dispatch_context *ctx, struct npt_command_ID3D12ProtectedResourceSession1_GetDesc1 *args)
{
}

static inline void
npt_encode_ID3D12ProtectedResourceSession1_GetDesc1_reply(struct npt_cs_encoder *enc,
                                                          const struct npt_command_ID3D12ProtectedResourceSession1_GetDesc1 *args)
{
    struct npt_reply_header _reply = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12ProtectedResourceSession1,
                                 NPT_METHOD_ID3D12ProtectedResourceSession1_GetDesc1),
        .cmd_return = 0,
    };
    npt_cs_encoder_write(enc, sizeof(_reply), &_reply, sizeof(_reply));
    npt_encode_D3D12_PROTECTED_RESOURCE_SESSION_DESC1(enc, &args->ret);
}

static inline void
npt_dispatch_ID3D12ProtectedResourceSession1_GetDesc1(struct npt_dispatch_context *ctx,
                                                      uint32_t cmd_flags,
                                                      uint64_t object_id)
{
    struct npt_command_ID3D12ProtectedResourceSession1_GetDesc1 args;
    memset(&args, 0, sizeof(args));

    npt_decode_ID3D12ProtectedResourceSession1_GetDesc1_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_ID3D12PROTECTEDRESOURCESESSION1);
    if (!args._self) {
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_ID3D12ProtectedResourceSession1_GetDesc1_args_handle(ctx, &args);

    PFN_ID3D12ProtectedResourceSession1_GetDesc1 _original = NPT_COM_VTBL_FUNC(
        PFN_ID3D12ProtectedResourceSession1_GetDesc1, npt_com_vtable(args._self),
        NPT_VTBL_ID3D12ProtectedResourceSession1_GetDesc1);

    if (ctx->id3d12protectedresourcesession1_dispatch_overrides && ctx->id3d12protectedresourcesession1_dispatch_overrides->GetDesc1) {
        args.ret = ctx->id3d12protectedresourcesession1_dispatch_overrides->GetDesc1(ctx, &args, _original);
    } else {
        args.ret = _original(args._self);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_ID3D12ProtectedResourceSession1_GetDesc1_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}


#pragma GCC diagnostic pop

#endif /* NPT_PROTOCOL_HOST_ID3D12PROTECTEDRESOURCESESSION_H */
