#!/usr/bin/env python3
"""Rebuild/check SM4 R/B-swap shader from shipped FXC tokens, no Windows compiler.

Use --write after modifying PSBlitSwapRB. The only intentional difference
from PSBlit is the sample resource swizzle; the production builder computes
all DXBC chunk sizes, signatures and checksum.
"""
from pathlib import Path
import argparse
import importlib.util
import os
import subprocess
import tempfile

TRITON = Path(__file__).resolve().parents[1]
ROOT = Path(__file__).resolve().parents[6]
spec = importlib.util.spec_from_file_location('d3d10_checks', ROOT / 'tests/vista/run-d3d10-compat.py')
module = importlib.util.module_from_spec(spec)
spec.loader.exec_module(module)
fixture, production, helper, windows = module.shader_inputs()
fixture = fixture[:fixture.index('int main(void)')]
main = r'''
static void emit(const char *name,const UINT select[4],BOOL alphaOne) {
 SIZE_T bytes;BYTE *dxbc=tritonD3D10BlitBytecode(g_tritonBlitPS,sizeof(g_tritonBlitPS),&bytes);
 CHECK(dxbc);UINT size;const UINT *original=chunk(dxbc,DXBC_BLOB_TYPE_SHDR,&size);
 UINT *code=malloc(size+20);CHECK(code);memcpy(code,original,size);UINT changed=0;
 UINT swizzle=0;for(UINT i=0;i<4;++i)swizzle|=select[i]<<(4+2*i);
 for(UINT at=2;at<code[1];at+=(code[at]>>24)&127) {
  if((code[at]&2047)==72) {
   CHECK(((code[at]>>24)&127)==11 && code[at+5]==0x00107e46u);
   code[at+5]=0x00107006u|swizzle;
   for(UINT i=0;i<4;++i)CHECK(((code[at+5]>>(4+2*i))&3)==select[i]);
   ++changed;
  }
 }
 CHECK(changed==1);
 if(alphaOne){
  UINT at=code[1]-1;CHECK(code[at]==0x0100003e);
  const UINT move[]={0x05000036,0x00102082,0,0x00004001,0x3f800000,0x0100003e};
  memcpy(code+at,move,sizeof(move));code[1]+=5;
 }
 SIZE_T rebuiltBytes;void *rebuilt=tritonBuildDxbc(code,code[1]*4,NULL,0,NULL,0,NULL,0,12,&rebuiltBytes);
 CHECK(rebuilt);validate(rebuilt,rebuiltBytes);free(dxbc);free(code);dxbc=rebuilt;bytes=rebuiltBytes;
 printf("const BYTE %s[] = {\n",name);
 for(SIZE_T i=0;i<bytes;++i){if(!(i%16))printf("    ");printf("%3u,%s",dxbc[i],i%16==15?"\n":" ");}
 puts("\n};\n");free(dxbc);
}
int main(void) {
 puts("/* Generated by tests/test_d3d10_blit_generation.py --write. */");
 const UINT bgra[]={2,1,0,3},raaa[]={0,3,3,3},rgaa[]={0,1,3,3};
 const UINT aara[]={3,3,0,3},agra[]={3,1,0,3},rgba[]={0,1,2,3};
 emit("g_tritonBlitSwapRBPS",bgra,FALSE);
 emit("g_tritonBlitRaaaPS",raaa,FALSE);
 emit("g_tritonBlitRgaaPS",rgaa,FALSE);
 emit("g_tritonBlitAaraPS",aara,FALSE);
 emit("g_tritonBlitAgraPS",agra,FALSE);
 emit("g_tritonBlitRgbOnePS",rgba,TRUE);
 emit("g_tritonBlitBgrOnePS",bgra,TRUE);
 return 0;
}
'''
text = (fixture + main).replace('// PRODUCTION_DXBC_IMPLEMENTATION', production).replace('// PRODUCTION_D3D10_SHADER_HELPERS', helper)
with tempfile.TemporaryDirectory(prefix='triton-blit-generator-') as tmp:
    work = Path(tmp)
    (work / 'windows.h').write_text(windows)
    (work / 'shader.c').write_text(text)
    subprocess.run([os.environ.get('CC', 'clang'), '-std=gnu11', '-O2', '-I', str(work),
                    '-I', str(TRITON), str(work / 'shader.c'), '-o', str(work / 'shader')], check=True)
    generated = subprocess.check_output([str(work / 'shader')], text=True)
    generated = '\n'.join(line.rstrip() for line in generated.splitlines()).rstrip() + '\n'
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--write', action='store_true')
args = parser.parse_args()
header = TRITON / 'tritonBlitShaders.h'
marker = '/* Generated by tests/test_d3d10_blit_generation.py --write. */'
old = header.read_text()
if args.write:
    header.write_text(old.split(marker)[0].rstrip() + '\n\n' + generated)
else:
    assert marker in old and old[old.index(marker):] == generated, 'generated swap shader is stale'
print('D3D10/D3D9 swap shader generation passed')
